name: SPARK Services
favicon: null
layout_spectrum: 0.76237
typography_spectrum: 0.06456
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#5084b3'
    - '#000000'
    - '#aedd27'
    - '#94e3fd'
    - '#00ff00'
  brandStrength: 0.5
  lightness: 0.8113170086871833
  saturation: 0.3125
  rhythmicContrast: 0.864596669562161
purpose: []
